Kata2 tests
ronhadad22/DevOpsSep22 pull request #10
Opened 2023-01-04 15:55 UTC by vitvizel

kata2 tests no final

2023-01-04 16:09 UTC, DannyAtal commented on python_katas/kata_2/test.py
>          pass
also about the TestJsonConfigsMerge, this one no one worked on it, we can if you like.
ask the group if someone want to join and we will build it.

2023-01-06 23:30 UTC, ronhadad22 requested changes

2023-01-06 23:30 UTC, ronhadad22 commented on python_katas/kata_2/test.py
> +            number = 0
no need to check 0

2023-01-06 23:30 UTC, ronhadad22 commented on python_katas/kata_2/test.py
> +       self.assertEqual(questions.most_frequent_name(file_path), "Most repeated name: Tawsha")
no need to return the prefix "most repeated name"
only the name need to return

2023-01-06 23:30 UTC, ronhadad22 commented on python_katas/kata_2/test.py
> +       file_path = "names2.txt"
there is no file "names2.txt"

2023-01-06 23:30 UTC, ronhadad22 commented on python_katas/kata_2/test.py
> +        self.assertEqual(questions.files_backup(dir_path), "/Users/gil/katas/DevOpsSep22/python_katas")
the func return  'backup_<dir_name>_<yyyy-mm-dd>.tar.gz' only

2023-01-06 23:30 UTC, ronhadad22 commented on python_katas/kata_2/test.py
good job

2023-01-06 23:30 UTC, ronhadad22 commented on python_katas/kata_2/test.py
> +    self.assertEqual(questions.longest_common_substring(str1, str2), a)
why no a2a
and why no quata ""

2023-01-06 23:30 UTC, ronhadad22 commented on python_katas/kata_2/test.py
> +#Shani
great job

2023-01-06 23:30 UTC, ronhadad22 commented on python_katas/kata_2/test.py
> +
the return to this func is None

2023-01-06 23:30 UTC, ronhadad22 commented on python_katas/kata_2/test.py
> +        self.assertEqual(questions.strong_pass(password), True)
great

2023-01-08 15:45 UTC, DannyAtal commented on python_katas/kata_2/test.py
> +       self.assertEqual(questions.most_frequent_name(file_path), "Most repeated name: Tawsha")
done

2023-01-08 15:45 UTC, DannyAtal commented on python_katas/kata_2/test.py
> +       file_path = "names2.txt"
done

2023-01-08 15:46 UTC, DannyAtal commented on python_katas/kata_2/test.py
> +
done

2023-01-11 15:29 UTC, DannyAtal reviewed
@ronhadad22 can you please check the PR again?
I just pushed the last test.

2023-01-12 18:14 UTC, ronhadad22 approved these changes

2023-01-12 18:15 UTC, merged