PR for Kata1 tests
ronhadad22/DevOpsSep22 pull request #8
Opened 2022-12-11 17:56 UTC by deanosaurx

Finished the last test.

2022-12-13 23:39 UTC, ronhadad22 commented on python_katas/kata_1/test.py
>          pass
what about empty str

2022-12-13 23:55 UTC, ronhadad22 requested changes
pls FIX all  the sections that with comments

2022-12-13 23:55 UTC, ronhadad22 commented on python_katas/kata_1/test.py
>          pass
the first element is NULL

2022-12-13 23:55 UTC, ronhadad22 commented on python_katas/kata_1/test.py
> +
func need to return bool

2022-12-13 23:55 UTC, ronhadad22 commented on python_katas/kata_1/test.py
the return value is a list!

2022-12-13 23:55 UTC, ronhadad22 commented on python_katas/kata_1/test.py
> +
the input is str!

2022-12-13 23:55 UTC, ronhadad22 commented on python_katas/kata_1/test.py
from the function description, "you can assume the input is a string containing numeric digits only"

2022-12-14 16:29 UTC, deanosaurx commented on python_katas/kata_1/test.py
>          pass
Added empty string with the latest commit

2022-12-15 07:42 UTC, bibiefart commented on python_katas/kata_1/test.py
> +
fixed
instaead of assertTrue/assertFalse i used assertEqual

2022-12-19 16:06 UTC, deanosaurx commented on python_katas/kata_1/test.py
Fixed by Dean.

2022-12-19 16:21 UTC, deanosaurx commented on python_katas/kata_1/test.py
> +
Fixed by Dean.

2022-12-19 23:11 UTC, ronhadad22 approved these changes

2022-12-19 23:12 UTC, merged